### PR TITLE
Cart management and wishlist management

### PR DESCRIPTION
**Pull request by NamrataRaikwar2002**
- Cart management
1. add to cart
2. after add to cart btn changes to go to cart.
3. remove from cart
4. cart bill.
5. quantity increase and decrease.
6. move to wishlist.
7. .image for empty cart.

- WishList management
1. add to  wishlist
2. remove from wishlist
3. move to cart
4.image for empty wishlist.

preview:https://sky-mart-app2022-git-cartmanagement-namrataraikwar2002.vercel.app/product-list

### CODE REVIEW

**Review by Aazam10 — APPROVED** [review]
Very clean and readable code

**Comment by prajapati-priyanka** [comment]
Hey, I have found a small bug. When I am adding same product to wishlist and cart page. After that when I go to the wishlist page and move the item to the cart, then that item get deleted in the wishlist page which is working fine but it is not getting added on the cart page. It's quantity should increase from one to two.

**Comment by prajapati-priyanka** [comment]
Screenshot (3)

Also, when I wishlisted a product, then I go to wishlist page from there when I am adding the product to the cart it is showing like this.

**Review by Tanjum786 — APPROVED** [review]
All look good.clean code
good to go .

**Comment by prajapati-priyanka** [comment]
Bugs has been resolved.
Functionalities are working Fine. 
Great work, @NamrataRaikwar2002

**Pull request merged**
